### ISSUE TITLE
env_logger doesn't output anything

### ISSUE THREAD

**Issue by IvanovOleg** [rust-cli/env_logger#311]
Hello,
I have a simple app that should log one string, but it doesn't:
**Cargo.toml:**
```toml
[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.11"
```
**main.rs:**
```rust
use log::info;
fn main() {
    env_logger::init();
    info!("program started");
    println!("Hello world!");
}
```
**Result:**
```shell
PS C:\Users\oliva\Documents\playground> cargo run
   Compiling playground v0.1.0 (C:\Users\oliva\Documents\playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
     Running `target\debug\playground.exe`
Hello world!
```
Tried using https://play.rust-lang.org/ as well, no output!
